### ISSUE TITLE
float-audits - Funding rate allows more tokens to be taken out than expected

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#109] opened 2023-03-25 12:26 UTC
float-audits

high

# Funding rate allows more tokens to be taken out than expected

## Summary

Current funding formula allows more tokens to be taken out by users who earning funding than what was deposited in by those users who paid the funding.

### Setup

Config values:

-   fundingFactor
-   fundingExponentFactor

Variable values before t<sub>0</sub>:
```math
\begin{align*}

    \text{FAPS}_{l} &= \text{dataStore.getInt}(\text{Keys.fundingAmountPerSizeKey(market, collateralToken=longToken, isLong=true)}) \
    \text{FAPS}_{s} &= \text{dataStore.getInt}(\text{Keys.fundingAmountPerSizeKey(market, collateralToken=longToken, isLong=false)}) \
    \text{OI}_{Ll} &= \text{dataStore.getUint}(\text{Keys.openInterestKey(market, collateralToken=longToken, isLong=true)}) \
    \text{OI}_{Ls} &= \text{dataStore.getUint}(\text{Keys.openInterestKey(market, collateralToken=longToken, isLong=false)}) \
    \text{OI}_{Sl} &= \text{dataStore.getUint}(\text{Keys.openInterestKey(market, collateralToken=shortToken, isLong=true)}) \
    \text{OI}_{Ss} &= \text{dataStore.getUint}(\text{Keys.openInterestKey(market, collateralToken=shortToken, isLong=false)}) \
    \text{OI}_{l} &= \text{OI}_{Ll} + \text{OI}_{Sl} \
    \text{OI}_{s} &= \text{OI}_{Ls} + \text{OI}_{Ss} \
    \text{OI} &= \text{OI}_{l} + \text{OI}_{s}
    \end{align*}
```

assume $\text{OI}_{l} \gt  \text{OI}\_{s}$ longs pay shorts

assume time between each t<sub>i</sub> is the same

<a id="orgc880f28"></a>

## Time t<sub>0</sub>

User1 & User2 create increase orders in same market.

<a id="orgb74fbfa"></a>

### User1 - long with long token collateral

1.  Set funding variables

Callpath:
```solidity
     OrderHandler.executeOrder
     OrderUtils.executeOrder
     IncreaseOrderUtils.processOrder
     IncreasePositionUtils.increasePosition
     PositionUtils.updateFundingAndBorrowingState
     MarketUtils.updateFundingAmountPerSize
```

Calculate nextFundingAmountPerSize:

```math
\begin{align*}
\text{diffUsd} &= \left|\text{OI}_{l} - \text{OI}_{s}\right| \\
\text{fundingFactorPerSecond} &= \text{fundingFactor} \cdot \frac{\text{diffUsd}^{\text{fundingExponentFactor}}}{\text{OI}} \\
\text{fundingUsd} &= \text{max}\left(\text{OI}_{l}, \text{OI}_{s}\right) \cdot \text{durationInSeconds} \cdot \text{fundingFactorPerSecond} \\
\text{fundingUsdForLongCollateral} &= \text{fundingUsd} \cdot \frac{\text{OI}_{Ll}}{\text{OI}_{l}} \\
\text{nextFundingAmountPerSize}_{\text{long}} &= \text{FAPS}_{l} + \frac{\text{fundingUsdForLongCollateral}}{\text{longTokenPrice.max} \cdot \text{OI}_{l}} \\
\text{nextFundingAmountPerSize}_{\text{short}} &= \text{FAPS}_{s} - \frac{\text{fundingUsdForLongCollateral}}{\text{longTokenPrice.max} \cdot \text{OI}_{s}} \\
\end{align*}
```
    
Variables set:
```math
\begin{align*}
\text{FAPS}_{l,t_0} &= \text{dataStore.setInt(Keys.fundingAmountPerSizeKey(market, collateralToken=longToken, isLong=true), value=nextFundingAmountPerSize<sub>long</sub>)} \\
\text{FAPS}_{s,t_0} &= \text{dataStore.setInt(Keys.fundingAmountPerSizeKey(market, collateralToken=longToken, isLong=false), value=nextFundingAmountPerSize<sub>short</sub>)}
\end{align*}
```
 assume hasPendingLongTokenFundingFee = false

2.  Set open interest variables

Callpath:
```solidity
     OrderHandler.executeOrder
     OrderUtils.executeOrder
     IncreaseOrderUtils.processOrder
     IncreasePositionUtils.increasePosition
     PositionUtils.updateOpenInterest
     MarketUtils.applyDeltaToOpenInterest
```
    
Variables set:
    
```math
\begin{aligned}
   & \text{dataStore.applyDeltaToUint(Keys.openInterestKey(market, collateralToken=longToken, isLong=true), delta=order.sizeDeltaUsd)} \\
    & \implies \text{OI}_{Ll,t0} = \text{OI}_{Ll} + \text{order.sizeDeltaUsd} \\
    & \text{OI}_{l,t0} = \text{OI}_{Ll,t0} + \text{OI}_{Sl} = \text{OI}_{Ll} + \text{OI}_{Sl} + \text{order.sizeDeltaUsd} = \text{OI}_l + \text{user1.order.sizeDeltaUsd} \\
    & \text{OI}_{s,t0} = \text{OI}_s \\
    & \text{OI}_{t0} = \text{OI}_{l,t0} + \text{OI}_s
\end{aligned}
```

3.  Set position variables

Callpath:
```solidity
     OrderHandler.executeOrder
     OrderUtils.executeOrder
     IncreaseOrderUtils.processOrder
     IncreasePositionUtils.increasePosition
```
 
Variables set:

```math
\begin{align*}
\text{position.setLongTokenFundingAmountPerSize(FAPS}_{l,t_0}\text{)} \\
\text{U1.P.S}_{t_0} = \text{position.setSizeInUsd(order.sizeInUsd)}
\end{align*}
```

### User2 - short with long token collateral

1.  Set funding variables

    durationInSeconds = 0 so no changes

2.  Set open interest variables

Callpath:
```solidity
     OrderHandler.executeOrder
     OrderUtils.executeOrder
     IncreaseOrderUtils.processOrder
     IncreasePositionUtils.increasePosition
     PositionUtils.updateOpenInterest
     MarketUtils.applyDeltaToOpenInterest
```

Variables set:
```math
\begin{aligned}
& \text{dataStore.applyDeltaToUint(Keys.openInterestKey(market, collateralToken=longToken, isLong=false), delta=order.sizeDeltaUsd)} \\
& \implies \text{OI}_{\text{Ls},t_0} = \text{OI}_{\text{Ls}} + \text{order.sizeDeltaUsd} \\
& \text{OI}_{\text{l},t_0} = \text{OI}_{\text{Ll},t_0} + \text{OI}_{\text{Sl}} = \text{OI}_{\text{Ll}} + \text{OI}_{\text{Sl}} + \text{user1.order.sizeDeltaUsd} = \text{OI}_{\text{l}} + \text{user1.order.sizeDeltaUsd} \\
& \text{OI}_{\text{s},t0} = \text{OI}_{\text{Ls}} + \text{OI}_{\text{Ss}} = \text{OI}_{\text{Ls}} + \text{OI}_{\text{Ss}} + \text{order.sizeDeltaUsd} = \text{OI}_{\text{s}} + \text{order.sizeDeltaUsd} \\
& \text{OI}_{t_0} = \text{OI}_{\text{l},t_0} + \text{OI}_{\text{s}}
\end{aligned}
```

3.  Set position variables

Variables set:
```math
\begin{aligned}
& \text{position.setLongTokenFundingAmountPerSize(FAPS}_{s,t_0}\text{)} \\
& \text{U2.P.S}_{t_0} = \text{position.setSizeInUsd(order.sizeInUsd)}
\end{aligned}
```

## Time t<sub>1</sub>

User1 creates decrease order to exit long position.

### Set funding variables

Callpath:
```solidity
 OrderHandler.executeOrder
 OrderUtils.executeOrder
 DecreaseOrderUtils.processOrder
 DecreasePositionUtils.decreasePosition
 PositionUtils.updateFundingAndBorrowingState
 MarketUtils.updateFundingAmountPerSize
```

Calculate nextFundingAmountPerSize:

```math
\begin{aligned}
& \text{diffUsd} = \left| \text{OI}_{l, t0} - \text{OI}_{s, t0} \right| \\
& \text{fundingFactorPerSecond} = \text{fundingFactor} \cdot \text{diffUsd}^{\text{fundingExponentFactor}} / \text{OI}_{t0} \\
& \text{fundingUsd} = \max\left(\text{OI}_{l, t0}, \text{OI}_{s, t0}\right) \cdot \text{durationInSeconds} \cdot \text{fundingFactorPerSecond} \\
& \text{fundingUsdForLongCollateral} = \text{fundingUsd} \cdot \text{OI}_{Ll, t0} / \text{OI}_{l, t0} \\
& \text{nextFundingAmountPerSize}_{\text{long}} = \text{FAPS}_{l, t0} + \text{fundingUsdForLongCollateral} / \left(\text{longTokenPrice.max} \cdot \text{OI}_{l, t0}\right) \\
& \text{nextFundingAmountPerSize}_{\text{short}} = \text{FAPS}_{s, t0} - \text{fundingUsdForLongCollateral} / \left(\text{longTokenPrice.max} \cdot \text{OI}_{s, t0}\right)
\end{aligned}
```

Variables set:
```math
\begin{align*}
\text{FAPS}_{l,t_1} &= \text{dataStore.setInt(Keys.fundingAmountPerSizeKey(market, collateralToken=longToken, isLong=true), value=nextFundingAmountPerSize}_{\text{long}}\text{)} \\
\text{FAPS}_{s,t_1} &= \text{dataStore.setInt(Keys.fundingAmountPerSizeKey(market, collateralToken=longToken, isLong=false), value=nextFundingAmountPerSize}_{\text{short}}\text{)}
\end{align*}
```

assume hasPendingLongTokenFundingFee = false

### Set open interest variables

Callpath:
```solidity
 OrderHandler.executeOrder
 OrderUtils.executeOrder
 DecreaseOrderUtils.processOrder
 DecreasePositionUtils.decreasePosition
 PositionUtils.updateOpenInterest
 MarketUtils.applyDeltaToOpenInterest
```

Variables set:
```math
\begin{aligned}
& \text{dataStore.applyDeltaToUint(Keys.openInterestKey(market, collateralToken=longToken, isLong=false), delta=-order.sizeDeltaUsd)} \\
& \implies \text{OI}_{\text{Ll},t1} = \text{OI}_{\text{Ll},t0} - \text{order.sizeDeltaUsd} \\
& \text{OI}_{\text{l},t1} = \text{OI}_{\text{Ll},t1} + \text{OI}_{\text{Ls},t0} \\
& \text{OI}_{\text{s},t1} = \text{OI}_{\text{s},t0} \\
& \text{OI}_{t1} = \text{OI}_{\text{l},t1} + \text{OI}_{\text{s},t0}
\end{aligned}
```

### Calculate funding fees

Callpath:
```solidity
 OrderHandler.executeOrder
 OrderUtils.executeOrder
 DecreaseOrderUtils.processOrder
 DecreasePositionUtils.decreasePosition
 DecreasePositionCollateralUtils.processCollateral
 PositionPricingUtils.getPositionFees
```
Variables set:
```math
\begin{aligned}
    &\text{longTokenFundingFeeAmount} = \text{U1.P.S}_{t0} \cdot (\text{latestLongTokenFundingAmountPerSize} - \text{position.longTokenFundingAmountPerSize}) \\
    &\implies \text{longTokenFundingFeeAmount} = \text{U1.P.S}_{t0} \cdot (\text{FAPS}_{\text{l},t1} - \text{FAPS}_{\text{l},t0})
\end{aligned}

```

Note on: FAPS<sub>l</sub><sub>t1</sub> - FAPS<sub>l</sub><sub>t0</sub>
```math
\begin{aligned}
    \text{FAPS}_{\text{l},t1} &= \text{FAPS}_{\text{l},t0} + \frac{\text{fundingUsdForLongCollateral}}{\text{longTokenPrice.max} \cdot \text{OI}_{\text{l},t0}} \\
    &\implies \text{FAPS}_{\text{l},t1} - \text{FAPS}_{\text{l},t0} = \frac{\text{fundingUsdForLongCollateral}}{\text{longTokenPrice.max} \cdot \text{OI}_{\text{l},t0}} \\
    &\implies \text{FAPS}_{\text{l},t1} - \text{FAPS}_{\text{l},t0} > 0 \\
    &\implies \text{user pays funding}
\end{aligned}
```

### Notes

Since user pays funding:

-   longTokenFundingFeeAmount is subtracted from outputAmount, which is the number of tokens that will be sent back to the user, and so the funding fee tokens stay in the MarketToken contract.
-   longTokenFundingFeeAmount is subtracted from collateralAmount, so these tokens are not tracked anymore in any variables.

<a id="org46a889d"></a>

## Time t<sub>2</sub>

User2 creates decrease order to exit everything.

<a id="org801cccb"></a>

### Set funding variables

Callpath:
```solidity
 OrderHandler.executeOrder
 OrderUtils.executeOrder
 DecreaseOrderUtils.processOrder
 DecreasePositionUtils.decreasePosition
 PositionUtils.updateFundingAndBorrowingState
 MarketUtils.updateFundingAmountPerSize
```
Calculate nextFundingAmountPerSize:
```math
\begin{aligned}
    \text{diffUsd} &= |\text{OI}_{\text{l},t1} - \text{OI}_{\text{s},t1}| \\
    \text{fundingFactorPerSecond} &= \text{fundingFactor} \cdot \frac{\text{diffUsd}^\text{fundingExponentFactor}}{\text{OI}_{t1}} \\
    \text{fundingUsd} &= \max(\text{OI}_{\text{l},t1}, \text{OI}_{\text{s},t1}) \cdot \text{durationInSeconds} \cdot \text{fundingFactorPerSecond} \\
    \text{fundingUsdForLongCollateral} &= \frac{\text{fundingUsd} \cdot \text{OI}_{\text{Ll},t1}}{\text{OI}_{\text{l},t1}} \\
    \text{nextFundingAmountPerSize}_{\text{long}} &= \text{FAPS}_{\text{l},t1} + \frac{\text{fundingUsdForLongCollateral}}{\text{longTokenPrice.max} \cdot \text{OI}_{\text{l},t1}} \\
    \text{nextFundingAmountPerSize}_{\text{short}} &= \text{FAPS}_{\text{s},t1} - \frac{\text{fundingUsdForLongCollateral}}{\text{longTokenPrice.max} \cdot \text{OI}_{\text{s},t1}}
\end{aligned}
```

Variables set:
```math
\begin{align*}
\text{FAPS}_{l,t2} &= \text{dataStore.setInt}\big(\text{Keys.fundingAmountPerSizeKey}(market, \text{collateralToken}=longToken, \text{isLong}=\text{true}), \text{value}= \text{nextFundingAmountPerSize}_{\text{long}}\big)\\
\text{FAPS}_{s,t2} &= \text{dataStore.setInt}\big(\text{Keys.fundingAmountPerSizeKey}(market, \text{collateralToken}=longToken, \text{isLong}=\text{false}), \text{value}= \text{nextFundingAmountPerSize}_{\text{short}}\big)\\
\end{align*}
```

assume hasPendingLongTokenFundingFee = false

### Calculate funding fees

Callpath:
```solidity
 OrderHandler.executeOrder
 OrderUtils.executeOrder
 DecreaseOrderUtils.processOrder
 DecreasePositionUtils.decreasePosition
 DecreasePositionCollateralUtils.processCollateral
 PositionPricingUtils.getPositionFees
```
Variables set:

```math
\begin{align*}
    &\text{longTokenFundingFeeAmount} = \text{U2.P.S}_{t0} \cdot (\text{latestLongTokenFundingAmountPerSize} - \text{position.longTokenFundingAmountPerSize}) \\
    &\text{longTokenFundingFeeAmount} = \text{U2.P.S}_{t0} \cdot (\text{FAPS}_{s,t2} - \text{FAPS}_{s,t0}) \\
\end{align*}
```

Note on: $\text{FAPS}_{s,t\_2} - \text{FAPS}\_{s,t\_0}$

```math
\begin{align*}
    &\text{FAPS}_{s,t2} = \text{FAPS}_{s,t1} - \frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \cdot \text{OI}_{s,t1}} \\
    &\text{FAPS}_{s,t1} = \text{FAPS}_{s,t0} - \frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \cdot \text{OI}_{s,t0}} \\
    &\Rightarrow \text{FAPS}_{s,t2} - \text{FAPS}_{s,t0} = - \frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \cdot \text{OI}_{s,t1}} - \frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \cdot \text{OI}_{s,t0}} \\
    &\Rightarrow \text{FAPS}_{s,t2} - \text{FAPS}_{s,t0} < 0 \\
    &\Rightarrow \text{user gets funding} \\
    &\Rightarrow \text{claimableLongTokenAmount} = |\text{longTokenFundingFeeAmount}|
\end{align*}
```

<a id="org2509e2b"></a>

### Update claimableCollateralAmount

Callpath:
```solidity
 OrderHandler.executeOrder
 OrderUtils.executeOrder
 DecreaseOrderUtils.processOrder
 DecreasePositionUtils.decreasePosition
 PositionUtils.incrementClaimableFundingAmount
 MarketUtils.incrementClaimableFundingAmount
```
Variables set:

$\text{dataStore.incrementUint(Keys.claimableFundingAmountKey(market, token=longToken, account), delta=longTokenFundingFeeAmount)}$

<a id="orgcadc1c7"></a>

### Compare funding amounts for user1 and user2

```math
\begin{align*}
\text{user1.longTokenFundingFeeAmount} &= \frac{\text{U1.P.S}_{t0} \times \text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{l,t0}} \\
\text{user2.claimableLongTokenAmount} &= \left|\text{U2.P.S}_{t0} \times \left(-\frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \times \text{OI}_{s,t1}} - \frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{s,t0}}\right)\right| \\
&= \text{U2.P.S}_{t0} \times \left(\frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \times \text{OI}_{s,t1}} + \frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{s,t0}}\right)
\end{align*}
```

assume $\text{U1.P.S}\_{t\_0} = \text{U2.P.S}\_{t\_0} = S$

then
```math
\begin{aligned}
&\text{user2.claimableLongTokenAmount} - \text{user1.longTokenFundingFeeAmount} = \\ 
&S \cdot \left(\frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max}} \cdot \left(\frac{1}{\text{OI}_{s,t0}} - \frac{1}{\text{OI}_{l,t0}}\right) + \frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \cdot \text{OI}_{s,t1}}\right)
\end{aligned}
```

Expand the following variables

```math
\begin{align*}
    OI_{l,t0} &= OI_{l} + \text{user1.order.sizeDeltaUsd} = OI_{l} + S \\
    OI_{s,t0} &= OI_{s} + \text{user2.order.sizeDeltaUsd} = OI_{s} + S
\end{align*}
```

longs pay shorts $\iff \text{OI}\_l > \text{OI}_s$

So $\text{OI}\_{l,t\_0} > \text{OI}\_{s,t\_0}$

So 
```math
\begin{equation}
\frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max}} \cdot \left( \frac{1}{\text{OI}_{s,t0}} - \frac{1}{\text{OI}_{l,t0}} \right) > 0
\end{equation}
```

Also, clearly 
```math
\frac{\text{fundingUsdForLongCollateral}\_{t\_2}}{\text{longTokenPrice}\_{t\_2}\text{.max} \times \text{OI}\_{s,t\_1}} > 0
```

So we have a non-zero difference which means more tokens can be claimed by user2 than user1 provided.

## Code Snippet

LoC: https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/market/MarketUtils.sol#L912-L1013

## Tool used

Manual Review

## Recommendation

Recommendation here is either
- change funding formula so that no user can claim more tokens in form of funding that other users have provided.
- alternatively have a backup pool that offers tokens when funding can't be paid entirely

**Comment by IllIllI000** [comment] 2023-04-18 07:02
For this part:
```math
\begin{align*}
\text{user1.longTokenFundingFeeAmount} &= \frac{\text{U1.P.S}_{t0} \times \text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{l,t0}} \\
\text{user2.claimableLongTokenAmount} &= \left|\text{U2.P.S}_{t0} \times \left(-\frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \times \text{OI}_{s,t1}} - \frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{s,t0}}\right)\right| \\
&= \text{U2.P.S}_{t0} \times \left(\frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \times \text{OI}_{s,t1}} + \frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{s,t0}}\right)
\end{align*}
```

The expansion of:
```math
\text{user2.claimableLongTokenAmount} - \text{user1.longTokenFundingFeeAmount}
```
is:
```math
\begin{align*}
(\text{U2.P.S}_{t0} \times \left(\frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \times \text{OI}_{s,t1}} + \frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{s,t0}}\right))
-
\frac{\text{U1.P.S}_{t0} \times \text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{l,t0}} \\
\end{align*}
```
which reduces to:
```math
\begin{align*}
(\text{S} \times \left(\frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \times \text{OI}_{s,t1}} + \frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{s,t0}}\right))
-
\frac{\text{S} \times \text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{l,t0}} \\
\end{align*}
```
and:
```math
\begin{align*}
(\text{S} \times (\left(\frac{\text{fundingUsdForLongCollateral}_{t2}}{\text{longTokenPrice}_{t2}\text{.max} \times \text{OI}_{s,t1}} + \frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{s,t0}}\right)
-
\frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max} \times \text{OI}_{l,t0}}) \\
\end{align*}
```
The issue submission pulls out part of the the second and third fractional terms, but doing this pulls part of `user2.claimableLongTokenAmount` into `user1.longTokenFundingFeeAmount`, which means the following inequalities do not have any bearing on whether there is a mismatch of the amounts:
```math
\begin{equation}
\frac{\text{fundingUsdForLongCollateral}_{t1}}{\text{longTokenPrice}_{t1}\text{.max}} \cdot \left( \frac{1}{\text{OI}_{s,t0}} - \frac{1}{\text{OI}_{l,t0}} \right) > 0
\end{equation}
,

\frac{\text{fundingUsdForLongCollateral}\_{t\_2}}{\text{longTokenPrice}\_{t\_2}\text{.max} \times \text{OI}\_{s,t\_1}} > 0

```
Furthermore, the finding says:

assume $\text{U1.P.S}\_{t\_0} = \text{U2.P.S}\_{t\_0} = S$

as well as:

longs pay shorts $\iff \text{OI}\_l > \text{OI}_s$
So $\text{OI}\_{l,t\_0} > \text{OI}\_{s,t\_0}$

which is contradictory, because the position sizes are the same at t0 and since the collateral is the same, the OI is the same. Therefore this subtraction is zero, not positive, since at t0 the open interest is equal:
```math
\frac{1}{\text{OI}_{s,t0}} - \frac{1}{\text{OI}_{l,t0}}
```

This finding looks invalid. Can we get a comment from the submitter?

**Comment by Stentonian** [comment] 2023-04-18 14:16
Hi @IllIllI000 thanks for the deep dive and the comment! Will reply to the 2 points you made..

### 1. Meaning of the constructed variable

This is the point in question:

> The issue submission pulls out part of the the second and third fractional terms, but doing this pulls part of user2.claimableLongTokenAmount into user1.longTokenFundingFeeAmount, which means the following inequalities do not have any bearing on whether there is a mismatch of the amounts:

The constructed value `user2.claimableLongTokenAmount - user1.longTokenFundingFeeAmount` is the difference in what user 2 is able to claim and what user 1 is providing. It is a single value so it does not matter how the equation is rearranged implicitly, and so I don't understand what logical deduction is used to get from *"but doing this pulls part of user2.claimableLongTokenAmount into user1.longTokenFundingFeeAmount"* to *"the following inequalities do not have any bearing on whether there is a mismatch of the amounts"*. Would you be able to elaborate? Also, what exactly do you mean by the word 'amounts'? There are quite a few variables so I'm not sure which one(s) you are referring to exactly.

### 2. Logic following the constructed variable

This is the point in question:

> which is contradictory, because the position sizes are the same at t0 and since the collateral is the same, the OI is the same. 

Just before t_0 there are no positions for user 1 or 2. This does not mean that there are no positions open in general for the market, which means the open interest of the long and short sides (`OI_l` & `OI_s`) need not be 0; the only restriction on the open interest values (which was stated in the first section of the finding) is that `OI_l > OI_s` (which is equivalent in the code to longs paying shorts) and is a completely valid state for the market to be in.

At t_0 user 1 and 2 create positions (assumed to be of the same USD size `S`) and the position sizes are used to update the open interest values giving `OI_l,t0` & `OI_s,t0`. Since `OI_l > OI_s` and they are both increased by `S` we have `OI_l,t0 > OI_s,t0`.

**Comment by IllIllI000** [comment] 2023-04-18 14:23
@Stentonian going through each of the steps of your proof takes an extremely long time and it's easy to miss something. Can you provide a plain English explanation of what the problem is? Do you have a test that will show the issue? Both I and the sponsor weren't able to tell from what has been provided so far.

**Comment by xvi10** [comment] 2023-04-19 07:42
hi @Stentonian, thank you for elaborating on this, agree with @IllIllI000 that a PoC test would help us understand the issue much better

**Comment by xvi10** [comment] 2023-04-21 02:24
I believe the only reason for a difference would be due to a rounding issue, a fix for the rounding issue: https://github.com/gmx-io/gmx-synthetics/commit/8e5c776546b1eb3da46ae824119f6c797354a640

**Comment by IllIllI000** [comment] 2023-04-21 07:33
as discussed in #67, this issue doesn't mention rounding, nor does it mention units of precision anywhere, so I don't see how this can be a description of a rounding issue. Still waiting to hear a very clear explanation of the issue from the submitter

**Comment by hrishibhat** [comment] 2023-04-21 17:21
Based on the above comments & discussions with the Lead and the Sponsor, Sherlock was unable to identify & validate the issue raised in the submission given the nature of its complexity. 
Additionally, the Watson was unable to provide further clarification within the stipulated time, due to constraints of their own. 
Considering all of the above, Sherlock has decided close this issue.

**Closed by hrishibhat** 2023-04-21 17:21 UTC
Labels: High, Sponsor Confirmed, Will Fix, Reward
